FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app
EXPOSE 80
EXPOSE 443

# Copy everything else and build
COPY . ./
WORKDIR /app/api/src/referenceApp.Api
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
WORKDIR /app
COPY --from=build /app/api/src/referenceApp.Api/out ./
ENTRYPOINT ["dotnet", "referenceApp.Api.dll"]